\documentclass[11pt]{article}
\usepackage{fullpage,graphicx,float,amsmath,enumitem,hyperref}
\setlist{parsep=5.5pt}
\setlength{\parindent}{0pt}
\setlength{\parskip}{\baselineskip}

\usepackage{fancyhdr}
\pagestyle{fancy}
\lhead{EDA}
\rhead{Consulting Seminar FALL 2016}
\setlength{\headheight}{18pt}
\setlength{\headsep}{2pt}

\title{EDA}
\author{Nnamdi, Paul, Andrea}
\date{\today}

\begin{document}
\maketitle

<<setup, echo = FALSE, message = FALSE, cache = FALSE>>=
library(knitr)
opts_chunk$set(echo = FALSE, comment = NA, fig.align = "center",
               fig.width = 6.5, fig.height = 4, fig.pos = "H",
               size = "footnotesize", dev = "pdf",
               dev.args = list(pointsize = 11))
knit_theme$set("print")

library(xtable)
options(xtable.table.placement = "H", xtable.caption.placement = "top",
        width = 80, scipen = 1, show.signif.stars = FALSE)

library(TSA)#harmonic()
library(mgcv)#gam()
library(nlme)#gls()
library(mosaic)#shuffle()
library(car)#ss
require(qtl)
@


{\bf We need to know exactly which phenotypes he would like assessed. His pairs plot is too small to read.}
<<readin, include=FALSE>>=
#change to your file path
setwd("C:/Users/Andrea Mack/Desktop/mack_hub/course_work/Consulting Seminar/seminar_f16/datasent102516")

bz15 <- read.csv("Final Data Files-lodging files 10-13-2016-2015bz.csv")
dim(bz15)

summary(complete.cases(bz15))
summary(bz15)

str(bz15.pheno)
colnames(bz15.pheno) <- c("avg.logding", "avg.height", "yield")
bz15.pheno$yield <- as.numeric(as.character(bz15.pheno$yield))


#for now, let's just look at lodging, height, and yield

bz15.pheno <- bz15[,2:4]

@

<<initial.plots>>=
pairs(bz15.pheno)
str(bz15.pheno)

boxplot(bz15.pheno)


data(hyper)
summary(hyper)
plotPheno(bz15.pheno)
@

<<lod.perm, cache = TRUE>>=

#from p. 117 broman
data(hyper)

str(hyper)

#first see p. 95, need to calculate lod at each qtl observed
#this section has a good explanation of lod
#go back and read this section!
#describes lod and what scanone is doing
out.em <- scanone(hyper, method = "em")

#hyper is a list of 2
#one list is the genotype data nested in each marker
#there is also a map objecte nested in the geno data
#the other is the phenotype data which is a dataframe

#criteria:: backcrossed (genotyping?)

#obtain qtl genotype probabilities
hyper <- calc.genoprob(hyper, step=1, error.prob=0.001)

#do the permutation test
operm <- scanone(hyper, n.perm=1000, verbose=FALSE)

#if selective genotyping done (define and ask Jamin) then 
#1) strata <- c(their names)
#2) scanone(~., perm.strata=strat, ~.)
#see p.118

#gives the genome scan adjusted pvalues for each lod peak
summary(out.em,perms = operm, alpha=0.1, pvalues = TRUE)

#surely, a confidence interval for the pvalue is better than a 
#strict cut off
#at each loci, the pvalue is below the threshold or not -- binom

#return the CI for the pvalue at D4Mit164
binom.test(0,1000)$conf.int


summary(out.em)
@


\end{document}
